// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package db

import (
	"context"
)

const pingDatabase = `-- name: PingDatabase :one
SELECT 1::int AS ping
`

func (q *Queries) PingDatabase(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, pingDatabase)
	var ping int32
	err := row.Scan(&ping)
	return ping, err
}
